export default{
	//CPHeader.vue导航模块
	SET_PATH:'SET_PATH',
	DEL_PATH:'DEL_PATH',
	CLEAR_PATH:'CLEAR_PATH',
	JUMPTO_PATH:'JUMPTO_PATH',
	//主页加载数据

	//style模块
	TOGGLE_COMPONENT:'TOGGLE_COMPONENT',
	HEAD_BGCOLOR:'HRAD_BGCOLOR',
	TOGGLE_HOME_FIXED:'TOGGLE_HOME_FIXED',
	//博客模块
	//状态管理
	BAR_MSG:'BAR_MSG',
	USER_SETINFOR:'USER_SETINFOR'
};